input {
    tcp {
        port => 5044
        codec => json
    }
}

output {
    elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "fast-food-simulator-logs"
    }
    stdout { codec => rubydebug }
}